<a href="https://colab.research.google.com/github/SamShinwari/Advanced-AI-Bootcamp-2026/blob/main/Student_Performance_Prediction_Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Student Performance Prediction Mini Project

In [1]:
import numpy as np
import pandas as pd

## Task 1: Create a Dataset of 10 Students

We will create a dataset of 10 students with their marks in Math, Physics, and Programming.

In [2]:
# Create sample data for 10 students
data = {
    'Math Marks': np.random.randint(40, 100, 10),
    'Physics Marks': np.random.randint(35, 95, 10),
    'Programming Marks': np.random.randint(50, 100, 10)
}
students_df = pd.DataFrame(data)
display(students_df)

   Math Marks  Physics Marks  Programming Marks
0          93             79                 89
1          75             49                 90
2          98             53                 73
3          78             86                 73
4          60             62                 78
5          96             91                 72
6          68             46                 99
7          91             46                 81
8          83             43                 53
9          74             77                 82

## Task 2: Store the Data in a Matrix

We will convert the Pandas DataFrame into a NumPy matrix (array) for easier mathematical operations.

In [3]:
student_data_matrix = students_df.values
print("Student Data Matrix Shape:", student_data_matrix.shape)
print("\nStudent Data Matrix:\n", student_data_matrix)

Student Data Matrix Shape: (10, 3)

Student Data Matrix:
 [[93 79 89]
 [75 49 90]
 [98 53 73]
 [78 86 73]
 [60 62 78]
 [96 91 72]
 [68 46 99]
 [91 46 81]
 [83 43 53]
 [74 77 82]]

## Task 3: Create a Weight Matrix

We will create a weight matrix. This matrix will represent the importance or contribution of each subject to the overall performance. For example, we might decide that Programming is more important than Math or Physics. The number of rows in the weight matrix should match the number of features (subjects) in our student data.

In [4]:
# Let's assume weights for Math, Physics, Programming respectively.
# For example, Programming might have a higher weight.
weights = np.array([
    [0.3],  # Weight for Math
    [0.3],  # Weight for Physics
    [0.4]   # Weight for Programming
])

weight_matrix = weights
print("Weight Matrix Shape:", weight_matrix.shape)
print("\nWeight Matrix:\n", weight_matrix)

Weight Matrix Shape: (3, 1)

Weight Matrix:
 [[0.3]
 [0.3]
 [0.4]]

## Task 4: Multiply the Matrices

We will now multiply the student data matrix by the weight matrix. This operation combines each student's marks with the corresponding subject weights to get a weighted sum for each student. This is a core operation in neural networks, where inputs are multiplied by weights.

In [5]:
# Perform matrix multiplication
weighted_sum = np.dot(student_data_matrix, weight_matrix)
print("Weighted Sum Shape:", weighted_sum.shape)
print("\nWeighted Sum (before bias):\n", weighted_sum)

Weighted Sum Shape: (10, 1)

Weighted Sum (before bias):
 [[87.2]
 [73.2]
 [74.5]
 [78.4]
 [67.8]
 [84.9]
 [73.8]
 [73.5]
 [59. ]
 [78.1]]

## Task 5: Add a Bias Vector

A bias vector is added to the weighted sum. The bias allows the model to shift the activation function to the left or right, which can be crucial for fitting complex data patterns. It acts as an offset.

In [6]:
# Create a bias vector (one bias for each student, or a single bias broadcasted)
bias = np.array([5]) # A simple bias value

# Add the bias to the weighted sum
output_before_activation = weighted_sum + bias
print("Output Before Activation Shape:", output_before_activation.shape)
print("\nOutput Before Activation (with bias):\n", output_before_activation)

Output Before Activation Shape: (10, 1)

Output Before Activation (with bias):
 [[92.2]
 [78.2]
 [79.5]
 [83.4]
 [72.8]
 [89.9]
 [78.8]
 [78.5]
 [64. ]
 [83.1]]

## Task 6: Apply the ReLU Activation Function

The Rectified Linear Unit (ReLU) is a popular activation function in neural networks. It introduces non-linearity, which is essential for models to learn complex relationships. ReLU simply outputs the input if it's positive, and zero otherwise.

In [7]:
# Apply the ReLU activation function
performance_scores = np.maximum(0, output_before_activation)
print("Performance Scores (after ReLU) Shape:", performance_scores.shape)
print("\nPerformance Scores (after ReLU):\n", performance_scores)

Performance Scores (after ReLU) Shape: (10, 1)

Performance Scores (after ReLU):
 [[92.2]
 [78.2]
 [79.5]
 [83.4]
 [72.8]
 [89.9]
 [78.8]
 [78.5]
 [64. ]
 [83.1]]

## Task 7: Interpret the Output as a Simple Performance Score

The final output, after applying the ReLU activation, can be interpreted as a simple performance score for each student. Higher scores indicate better performance based on the assigned weights and bias. This simulates a very basic single-layer neural network output.

In [8]:
# Add performance scores back to the DataFrame for better interpretation
students_df['Performance Score'] = performance_scores
display(students_df)

   Math Marks  Physics Marks  Programming Marks  Performance Score
0          93             79                 89               92.2
1          75             49                 90               78.2
2          98             53                 73               79.5
3          78             86                 73               83.4
4          60             62                 78               72.8
5          96             91                 72               89.9
6          68             46                 99               78.8
7          91             46                 81               78.5
8          83             43                 53               64.0
9          74             77                 82               83.1

---

# Practice Questions

## Theory Questions

### Why is matrix multiplication considered the core operation in neural networks?

Matrix multiplication is fundamental in neural networks because it efficiently represents the linear transformation of input features. Each neuron in a layer receives inputs from the previous layer, multiplies them by their respective weights, and sums them up. This entire process across all neurons in a layer can be compactly expressed as a single matrix multiplication operation between the input matrix and the weight matrix of that layer. This mathematical elegance allows for parallel computation and is highly optimized in modern hardware (like GPUs), making neural network training and inference feasible for large datasets and complex models.

### Explain the difference between element-wise multiplication and matrix multiplication.

*   **Element-wise multiplication (Hadamard product):** This operation takes two matrices of the *same dimensions* and produces a new matrix where each element is the product of the corresponding elements from the input matrices. For example, if A and B are both 2x2 matrices, the element at (i, j) in the result is A[i, j] * B[i, j]. This is often denoted by A ⊙ B.

*   **Matrix multiplication (dot product):** This operation takes two matrices, say A (dimensions m x n) and B (dimensions n x p), and produces a new matrix C (dimensions m x p). For the multiplication to be valid, the number of columns in the first matrix (n) must equal the number of rows in the second matrix (n). Each element C[i, j] in the resulting matrix is computed as the sum of the products of elements from the i-th row of A and the j-th column of B. This is the core operation in linear algebra and neural networks.

### Why is ReLU preferred over a simple linear function in deep neural networks?

ReLU (Rectified Linear Unit) is preferred over a simple linear function in deep neural networks for several key reasons:

1.  **Non-linearity:** A deep neural network composed solely of linear activation functions (like a simple linear function) would effectively be a single linear transformation, regardless of the number of layers. This means it could only learn linear relationships, severely limiting its ability to model complex, real-world data. ReLU introduces non-linearity, allowing deep networks to learn and approximate arbitrary complex functions.
2.  **Computational Efficiency:** ReLU is computationally very efficient to compute (just a `max(0, x)` operation) and its derivative is also simple (0 for negative inputs, 1 for positive inputs), which speeds up the backpropagation process during training.
3.  **Mitigates Vanishing Gradient Problem:** Unlike sigmoid or tanh functions which can suffer from vanishing gradients (where gradients become extremely small, slowing down or stopping learning in deeper layers), ReLU's derivative is a constant 1 for positive inputs, which helps in propagating gradients effectively through many layers.

### What is the purpose of adding a bias term?

The purpose of adding a bias term in neural networks (and linear models) is to allow the model to shift the activation function output independently of the input features. Without a bias term, the output of a neuron would always pass through the origin (0,0) in the input-output space. Adding a bias gives the model more flexibility to fit the data. It enables the activation function to be shifted along the x-axis, effectively allowing the model to learn a wider range of mappings and capture patterns that might not pass through the origin.

## Programming Questions

### 1. Create two random 4x4 matrices and multiply them.

In [9]:
matrix1 = np.random.rand(4, 4)
matrix2 = np.random.rand(4, 4)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

product_matrix = np.dot(matrix1, matrix2)
print("\nProduct Matrix (using np.dot):\n", product_matrix)

Matrix 1:
 [[0.13759001 0.88132822 0.01492628 0.64863571]
 [0.6277363  0.10220635 0.35921444 0.97263393]
 [0.26042358 0.72486906 0.50926614 0.34750281]
 [0.8988802  0.29651225 0.78562988 0.22024656]]

Matrix 2:
 [[0.1300723  0.90268772 0.73777408 0.70745589]
 [0.29794694 0.81542408 0.57459392 0.44466163]
 [0.78438728 0.53327458 0.63340955 0.46606357]
 [0.65920887 0.57824112 0.56771732 0.90690332]]

Product Matrix (using np.dot):
 [[0.71978009 1.22588471 0.98561236 1.08443818]
 [1.03503532 1.40396823 1.30156571 1.53904468]
 [0.87838523 1.29867596 1.12849652 1.0590615 ]
 [0.9666909  1.59950341 1.4562079  1.33366151]]

### 2. Write your own function to multiply two matrices without using NumPy.

In [10]:
def multiply_matrices_manual(A, B):
    # Get dimensions of matrices A and B
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Number of columns in A must be equal to number of rows in B")

    # Initialize the result matrix with zeros
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
    return result

# Example usage:
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8],
     [9, 10],
     [11, 12]]

manual_product = multiply_matrices_manual(A, B)
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nProduct Matrix (manual function):\n", manual_product)

# Verify with NumPy (optional)
np_A = np.array(A)
np_B = np.array(B)
np_product = np.dot(np_A, np_B)
print("\nProduct Matrix (NumPy verification):\n", np_product)

Matrix A:
 [[1, 2, 3], [4, 5, 6]]

Matrix B:
 [[7, 8], [9, 10], [11, 12]]

Product Matrix (manual function):
 [[58, 64], [139, 154]]

Product Matrix (NumPy verification):
 [[ 58  64]
 [139 154]]

### 3. Check if a given matrix is symmetric.

In [11]:
def is_symmetric(matrix):
    # A matrix must be square to be symmetric
    rows = len(matrix)
    cols = len(matrix[0])
    if rows != cols:
        return False

    # Check if matrix[i][j] == matrix[j][i] for all i, j
    for i in range(rows):
        for j in range(i + 1, cols): # Only check upper triangle to avoid redundant checks
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

# Example usage:
matrix_sym = [[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]]

matrix_nonsym = [[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]]

print("Matrix Symmetric:\n", np.array(matrix_sym))
print("Is symmetric?", is_symmetric(matrix_sym))

print("\nMatrix Non-Symmetric:\n", np.array(matrix_nonsym))
print("Is symmetric?", is_symmetric(matrix_nonsym))

Matrix Symmetric:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]
Is symmetric? True

Matrix Non-Symmetric:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Is symmetric? False

### 4. Create a 5x5 identity matrix.

In [12]:
# Using NumPy
identity_matrix_np = np.identity(5)
print("5x5 Identity Matrix (using NumPy):\n", identity_matrix_np)

# Manual implementation
def create_identity_matrix(size):
    matrix = [[0 for _ in range(size)] for _ in range(size)]
    for i in range(size):
        matrix[i][i] = 1
    return matrix

identity_matrix_manual = create_identity_matrix(5)
print("\n5x5 Identity Matrix (manual implementation):\n", np.array(identity_matrix_manual))

5x5 Identity Matrix (using NumPy):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

5x5 Identity Matrix (manual implementation):
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

### 5. Implement one layer of a neural network using matrix multiplication, bias addition, and ReLU.

In [13]:
def neural_network_layer(inputs, weights, bias):
    # Step 1: Matrix multiplication (inputs * weights)
    linear_output = np.dot(inputs, weights)

    # Step 2: Add bias
    biased_output = linear_output + bias

    # Step 3: Apply ReLU activation function
    activated_output = np.maximum(0, biased_output)

    return activated_output

# Define inputs (e.g., features for 3 samples, 4 features each)
# Each row is a sample, each column is a feature
inputs = np.array([
    [1.0, 0.5, 0.2, 0.8],  # Sample 1
    [0.3, 0.9, 0.1, 0.6],  # Sample 2
    [0.7, 0.2, 0.8, 0.4]   # Sample 3
])

# Define weights (e.g., 4 input features, 2 neurons in the current layer)
# Number of rows = number of input features
# Number of columns = number of neurons in the current layer
weights = np.array([
    [0.1, 0.4],  # Weights for feature 1
    [0.5, -0.2], # Weights for feature 2
    [0.3, 0.6],  # Weights for feature 3
    [-0.1, 0.7]  # Weights for feature 4
])

# Define bias (one bias for each neuron in the current layer)
bias = np.array([0.2, -0.3]) # Bias for neuron 1, Bias for neuron 2

print("Inputs Shape:", inputs.shape)
print("Weights Shape:", weights.shape)
print("Bias Shape:", bias.shape)

# Run the neural network layer
layer_output = neural_network_layer(inputs, weights, bias)

print("\nInputs:\n", inputs)
print("\nWeights:\n", weights)
print("\nBias:\n", bias)
print("\nOutput of the Neural Network Layer:\n", layer_output)

Inputs Shape: (3, 4)
Weights Shape: (4, 2)
Bias Shape: (2,)

Inputs:
 [[1.  0.5 0.2 0.8]
 [0.3 0.9 0.1 0.6]
 [0.7 0.2 0.8 0.4]]

Weights:
 [[ 0.1  0.4]
 [ 0.5 -0.2]
 [ 0.3  0.6]
 [-0.1  0.7]]

Bias:
 [ 0.2 -0.3]

Output of the Neural Network Layer:
 [[0.53 0.68]
 [0.65 0.12]
 [0.57 0.7 ]]